CREATE TABLE [dbo].[Parts_Purchases] (

	[PTPURITM_ItmId] int NULL, 
	[PTPURITM_PurId] varchar(8000) NULL, 
	[PTPURITM_ItmTyp] varchar(8000) NULL, 
	[PTPURITM_PtItm] varchar(8000) NULL, 
	[PTPURITM_Des] varchar(8000) NULL, 
	[PTPURITM_Reason] varchar(8000) NULL, 
	[PTPURITM_AmtCostOrder] float NULL, 
	[PTPURITM_AmtCostReceive] float NULL, 
	[PTPURITM_QtyOrder] float NULL, 
	[PTPURITM_QtyReceive] float NULL, 
	[PTPURITM_StockOrderRatio] float NULL, 
	[PTPURITM_AmtCostStock] float NULL, 
	[PTPURITM_QtyStock] float NULL, 
	[PTPURITM_EmpId] varchar(8000) NULL, 
	[PTPURITM_DateCreate] date NULL, 
	[PTPURITM_DateExpect] date NULL, 
	[PTPURITM_DateUpdate] date NULL, 
	[PTPURITM_Status] int NULL, 
	[PTPURITM_Acknowledgement] varchar(8000) NULL, 
	[PTPUR_VenName] varchar(8000) NULL, 
	[PTPUR_DateOrder] date NULL, 
	[PTPUR_PurTypId] varchar(8000) NULL, 
	[PTPUR_DateReceive] date NULL, 
	[COLOOKUP_Des1] varchar(8000) NULL, 
	[PTPUR_Location] varchar(8000) NULL, 
	[PTPUR_DaysOpen] int NULL, 
	[COEMP_EmpName] varchar(8000) NULL
);