CREATE TABLE [dbo].[Parts_Tape] (

	[VenPrtId] varchar(8000) NULL, 
	[SrcId] varchar(8000) NULL, 
	[Des] varchar(8000) NULL, 
	[ClaId] varchar(8000) NULL, 
	[Typ] int NULL, 
	[Sequence] int NULL, 
	[OrderPkg] int NULL, 
	[AmtCost] float NULL, 
	[AmtCost2] float NULL, 
	[AmtPrice1] float NULL, 
	[AmtPrice2] float NULL, 
	[AmtPrice3] float NULL, 
	[AmtPrice4] float NULL, 
	[AmtPrice5] float NULL, 
	[AmtPrice6] float NULL, 
	[AmtPrice7] float NULL, 
	[AmtPrice8] float NULL, 
	[CoreVenPrtId] varchar(8000) NULL, 
	[TapMisc1] varchar(8000) NULL, 
	[TapMisc2] varchar(8000) NULL, 
	[TapMisc3] varchar(8000) NULL, 
	[TapMisc4] varchar(8000) NULL, 
	[TapMisc5] varchar(8000) NULL, 
	[TapMisc6] varchar(8000) NULL, 
	[TapMisc7] varchar(8000) NULL, 
	[TapMisc8] varchar(8000) NULL, 
	[TapMisc9] varchar(8000) NULL, 
	[TapMisc10] varchar(8000) NULL, 
	[DateCreate] datetime2(6) NULL, 
	[DateUpdate] datetime2(6) NULL, 
	[OrderPkgTyp] int NULL
);