CREATE TABLE [dbo].[Parts_Sales] (

	[DateInvoice] datetime2(6) NULL, 
	[DateCreate] datetime2(6) NULL, 
	[DateUpdate] datetime2(6) NULL, 
	[EmpId] varchar(8000) NULL, 
	[Name] varchar(8000) NULL, 
	[SlsId] varchar(8000) NULL, 
	[EstimateSlsId] varchar(8000) NULL, 
	[InvoiceSlsId] varchar(8000) NULL, 
	[Origin] varchar(8000) NULL, 
	[PtItm] varchar(8000) NULL, 
	[Des] varchar(8000) NULL, 
	[ClaId] varchar(8000) NULL, 
	[SrcId] varchar(8000) NULL, 
	[ItmTyp] int NULL, 
	[ItmDes] varchar(8000) NULL, 
	[BrnId] varchar(8000) NULL, 
	[CusId] varchar(8000) NULL, 
	[BillCusId] varchar(8000) NULL, 
	[SlsTypId] varchar(8000) NULL, 
	[CusName] varchar(8000) NULL, 
	[BillCusName] varchar(8000) NULL, 
	[AmtCost] float NULL, 
	[AmtPrice] float NULL, 
	[AmtPriceSuggest] float NULL, 
	[AmtRebate] float NULL, 
	[QtyShip] float NULL, 
	[Status] int NULL, 
	[Extended Sales] float NULL, 
	[Extended Cost] float NULL, 
	[Reason] varchar(8000) NULL, 
	[PrtMisc5] varchar(8000) NULL, 
	[QtyOH] float NULL, 
	[QtyOO] float NULL, 
	[Core] varchar(8000) NULL, 
	[VenPrtId] varchar(8000) NULL, 
	[Posted] int NULL, 
	[CaPrtId] varchar(8000) NULL
);