table Date
	lineageTag: fc9e61d5-e96a-458c-b14a-b3096ee89920
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'COCUSAPV'[DateAuth] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence
		lineageTag: 43377f6e-a0f0-4423-b76b-f97dbda72682

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column Date
		isKey
		formatString: m/d/yyyy
		lineageTag: 061e96c8-05f5-4b35-abbf-5fbd1c7f9a88
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date

	column Year
		lineageTag: 44ccd27c-cbc4-4815-8001-bee642ca4ba4
		dataCategory: Years
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter Number'
		isHidden
		lineageTag: 2cae19a7-5ebd-4b36-b0f5-1556b333aeab
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter Number]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		lineageTag: 461b2a3e-e782-47c1-bd2b-bfe69902910d
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter]
		sortByColumn: 'Year Quarter Number'

	column Quarter
		lineageTag: ab275b2a-8a46-4444-8103-91c801053eb8
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Quarter]

	column 'Year Month'
		lineageTag: 36e64ebd-7936-4a78-88f5-e83c676880d9
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		isHidden
		lineageTag: c71591fc-14b5-41d5-9643-eb7e620727ce
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

		annotation SummarizationSetBy = Automatic

	column Month
		lineageTag: e4ae0c5a-0adb-4ca3-8708-8ca03297c67e
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Month Number'

	column 'Month Number'
		isHidden
		lineageTag: cc60e3f1-fd8d-4b83-963c-44c67e54ec12
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month Number]

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		isHidden
		lineageTag: 70628c23-2680-4419-b217-fc176626ab4f
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = DayOfWeek

		annotation SQLBI_FilterSafe = True

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		lineageTag: 3d2d14a2-d601-4f1b-8b84-d8b264c7da49
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_FilterSafe = True

	column DateWithTransactions
		isHidden
		lineageTag: 6d2cc538-3a3e-44d2-9718-83b9f3854563
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	hierarchy Calendar
		lineageTag: 3d8d9d78-29a5-4b10-b25f-5d6170a325f2

		level Year
			lineageTag: 9533b8f2-f100-44c7-9594-7944fffe18c6
			column: Year

		level Month
			lineageTag: 5702ade3-b00d-439f-800b-bda31520c351
			column: 'Year Month'

		level Date
			lineageTag: 63ec78e3-ee8c-4a76-8b6e-26aceddd4945
			column: Date

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Calendar

