table Date
	lineageTag: b9cb1e88-2b76-4d40-9635-4fbd0f5eff3b
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'Elite Extra'[Time Delivered] ), MAX ( 'Elite Extra'[Time Departed] ), MAX ( 'Elite Extra'[Delivery Date] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence
		lineageTag: 872a377e-720b-4c56-a72f-09a20aa51b3d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column Date
		isKey
		formatString: m/d/yyyy
		lineageTag: 91d8c2c1-1904-4685-830d-a028849d4af4
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date

	column Year
		formatString: 0
		lineageTag: 4d88b4e0-b374-4b16-b3d5-131c7e9defe6
		dataCategory: Years
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter Number'
		isHidden
		formatString: 0
		lineageTag: 0c313e97-1055-4c58-8cdc-60ce2e2eff5d
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter Number]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		lineageTag: d94467c7-b078-487d-8089-bb288e4a1050
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter]
		sortByColumn: 'Year Quarter Number'

	column Quarter
		lineageTag: 597435fe-a177-40ca-892f-da06ee9faab9
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Quarter]

	column 'Year Month'
		lineageTag: b9054467-cc60-4311-9515-59ec6d1b7c84
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		isHidden
		formatString: 0
		lineageTag: 4a490943-635c-4cac-9616-83ae466c956b
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

		annotation SummarizationSetBy = Automatic

	column Month
		lineageTag: 9954aa72-1374-4e6c-a5a2-2af4746f79a3
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Month Number'

	column 'Month Number'
		formatString: 0
		lineageTag: f696e67c-49ff-421a-81d1-b7b3ec2c0804
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month Number]

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		formatString: 0
		lineageTag: 71714400-6dc8-4c26-8e15-5ccc83c0db40
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = DayOfWeek

		annotation SQLBI_FilterSafe = True

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		lineageTag: 9f62bea7-7aa2-4054-8118-ece0b4ac6743
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_FilterSafe = True

	column DateWithTransactions
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0cdf6f4a-9d64-41df-945a-71ba5d6410cf
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	column 'Day of Month'
		formatString: 0
		lineageTag: 333544ab-54eb-4e0f-8874-b7396ad61143
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Month]

		annotation SummarizationSetBy = Automatic

	hierarchy Calendar
		lineageTag: 1ab865ed-5217-4884-8749-f8344ed5cd68

		level Year
			lineageTag: 586682ae-e489-4def-b321-29adc28a6573
			column: Year

		level Month
			lineageTag: 4a9def57-8837-49fc-8a44-ab3f8f3da217
			column: 'Year Month'

		level Date
			lineageTag: a21dd264-9bac-44d8-8786-5e3683b3e06b
			column: Date

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Calendar

