table table
	lineageTag: 1ff9b3be-e47f-49cd-bcfe-8345534c04a3

	column 'Session Id'
		dataType: string
		lineageTag: 3b262161-5d6f-46ff-853b-2c5f7f1bac12
		summarizeBy: none
		sourceColumn: Session Id

		annotation SummarizationSetBy = Automatic

	column 'From Name'
		dataType: string
		lineageTag: e559d6a2-224e-4d52-a2eb-6f0ace101486
		summarizeBy: none
		sourceColumn: From Name

		annotation SummarizationSetBy = Automatic

	column 'From Number'
		dataType: string
		lineageTag: 467ec04c-364f-41a7-afac-ff71c6c4dfcb
		summarizeBy: none
		sourceColumn: From Number

		annotation SummarizationSetBy = Automatic

	column 'To Name'
		dataType: string
		lineageTag: 8ff0e40f-9995-4017-a450-92a27e38d0f5
		summarizeBy: none
		sourceColumn: To Name

		annotation SummarizationSetBy = Automatic

	column 'To Number'
		dataType: string
		lineageTag: 92356ab1-3178-4a7e-b5aa-f7cdba9e263a
		summarizeBy: none
		sourceColumn: To Number

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: 011665ed-b091-4425-9bcd-4c9927774f19
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column 'Call Length'
		dataType: string
		lineageTag: f3958cdf-3c8a-4b76-929e-4772c38d75b0
		summarizeBy: none
		sourceColumn: Call Length

		annotation SummarizationSetBy = Automatic

	column 'Handle Time'
		dataType: string
		lineageTag: 51ec14ff-2da6-4320-a8a0-9e2b525fbd5c
		summarizeBy: none
		sourceColumn: Handle Time

		annotation SummarizationSetBy = Automatic

	column 'Call Start Time'
		dataType: string
		lineageTag: dcc373d5-f63f-46b8-8231-610e59c7e749
		summarizeBy: none
		sourceColumn: Call Start Time

		annotation SummarizationSetBy = Automatic

	column 'Call Direction'
		dataType: string
		lineageTag: 9e8caea9-2bcf-4c42-b923-bc65a2d4d04b
		summarizeBy: none
		sourceColumn: Call Direction

		annotation SummarizationSetBy = Automatic

	column Queue
		dataType: string
		lineageTag: 74ed8a6f-9ab0-411e-8984-9678f11b711d
		summarizeBy: none
		sourceColumn: Queue

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 943fcdcb-ab26-4c88-ba4e-bd9f5334bcbe
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition table = m
		mode: import
		source = ```
				let
				                    Source = SharePoint.Tables("https://bepensa.sharepoint.com/sites/BM-USA-IT", [Implementation= "2.0", ViewMode = "Default"]), 
				                    Navigation = Source{[Id="f0b133d8-b93d-497d-a4b5-67799870a39b"]}[Items],
				                    TableSchema = Table.Schema(Navigation),
				                    UserMultiTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "UserMulti"),
				UserMultiFieldNames = {"id", "value", "title", "email", "sip", "picture", "jobTitle", "department"},
				UserMultiTransforms = Table.AddColumn(UserMultiTypeRows, "UserMultiTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, UserMultiFieldNames), "title"), ", ") else null, Function.Type),
				UserMultiChanges = Table.ToRows(Table.SelectColumns(UserMultiTransforms, { "Name","UserMultiTransform"})),
				ExpandedUserMulti = Table.TransformColumns(Navigation, UserMultiChanges, null, MissingField.UseNull),
				                    UserTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "User"),
				UserFieldNames = {"id", "title", "email", "sip", "picture", "jobTitle", "department"},
				UserTransforms = Table.AddColumn(UserTypeRows, "UserTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, UserFieldNames), "title"), ", ") else null, Function.Type),
				UserChanges = Table.ToRows(Table.SelectColumns(UserTransforms, { "Name","UserTransform"})),
				ExpandedUser = Table.TransformColumns(ExpandedUserMulti, UserChanges, null, MissingField.UseNull),
				                    LookupTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "Lookup"),
				LookupFieldNames = {"lookupId", "lookupValue", "isSecretFieldValue"},
				LookupTransforms = Table.AddColumn(LookupTypeRows, "LookupTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, LookupFieldNames), "lookupValue"), ", ") else null, Function.Type),
				LookupChanges = Table.ToRows(Table.SelectColumns(LookupTransforms, { "Name","LookupTransform"})),
				ExpandedLookup = Table.TransformColumns(ExpandedUser, LookupChanges, null, MissingField.UseNull),
				                    TaxonomyFieldTypeTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "TaxonomyFieldType"),
				TaxonomyFieldTypeTransforms = Table.AddColumn(TaxonomyFieldTypeTypeRows, "TaxonomyFieldTypeTransform", each (name) => 
				                        if (name <> "") then @Text.Combine(Table.Column(Table.FromRecords({ name }), "Label")) else null, Function.Type),
				TaxonomyFieldTypeChanges = Table.ToRows(Table.SelectColumns(TaxonomyFieldTypeTransforms, { "Name","TaxonomyFieldTypeTransform"})),
				ExpandedTaxonomyFieldType = Table.TransformColumns(ExpandedLookup, TaxonomyFieldTypeChanges, null, MissingField.UseNull),
				                    LocationTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "Location"),
				LocationTransforms = Table.AddColumn(LocationTypeRows, "LocationTransform", each (name) => 
				                        if (name <> "") then @Text.Combine(Table.Column(Table.FromRecords({ name }), "DisplayName")) else null, Function.Type),
				LocationChanges = Table.ToRows(Table.SelectColumns(LocationTransforms, { "Name","LocationTransform"})),
				ExpandedLocation = Table.TransformColumns(ExpandedTaxonomyFieldType, LocationChanges, null, MissingField.UseNull),
				                    ThumbnailTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "Thumbnail"),
				ThumbnailTransforms = Table.AddColumn(ThumbnailTypeRows, "ThumbnailTransform", each (name) => 
				                        if (name <> "") then @Text.Combine(Table.Column(Table.FromRecords({ name }), "fileName")) else null, Function.Type),
				ThumbnailChanges = Table.ToRows(Table.SelectColumns(ThumbnailTransforms, { "Name","ThumbnailTransform"})),
				ExpandedThumbnail = Table.TransformColumns(ExpandedLocation, ThumbnailChanges, null, MissingField.UseNull),
				                    LookupMultiTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "LookupMulti"),
				LookupMultiFieldNames = {"lookupId", "lookupValue", "isSecretFieldValue"},
				LookupMultiTransforms = Table.AddColumn(LookupMultiTypeRows, "LookupMultiTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, LookupMultiFieldNames), "lookupValue"), ", ") else null, Function.Type),
				LookupMultiChanges = Table.ToRows(Table.SelectColumns(LookupMultiTransforms, { "Name","LookupMultiTransform"})),
				ExpandedLookupMulti = Table.TransformColumns(ExpandedThumbnail, LookupMultiChanges, null, MissingField.UseNull),
				                    TaxonomyFieldTypeMultiTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "TaxonomyFieldTypeMulti"),
				TaxonomyFieldTypeMultiFieldNames = {"Label", "TermID"},
				TaxonomyFieldTypeMultiTransforms = Table.AddColumn(TaxonomyFieldTypeMultiTypeRows, "TaxonomyFieldTypeMultiTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(Table.Column(Table.FromList(name, Record.FieldValues, TaxonomyFieldTypeMultiFieldNames), "Label"), ", ") else null, Function.Type),
				TaxonomyFieldTypeMultiChanges = Table.ToRows(Table.SelectColumns(TaxonomyFieldTypeMultiTransforms, { "Name","TaxonomyFieldTypeMultiTransform"})),
				ExpandedTaxonomyFieldTypeMulti = Table.TransformColumns(ExpandedLookupMulti, TaxonomyFieldTypeMultiChanges, null, MissingField.UseNull),
				                    MultiChoiceTypeRows = Table.SelectRows(TableSchema, each [NativeTypeName] = "MultiChoice"),
				MultiChoiceTransforms = Table.AddColumn(MultiChoiceTypeRows, "MultiChoiceTransform", each(name) => 
				                    if (name <> "") then @Text.Combine(name, ", ") else null, Function.Type),
				MultiChoiceChanges = Table.ToRows(Table.SelectColumns(MultiChoiceTransforms, { "Name","MultiChoiceTransform"})),
				ExpandedMultiChoice = Table.TransformColumns(ExpandedTaxonomyFieldTypeMulti, MultiChoiceChanges, null, MissingField.UseNull)
				                in ExpandedMultiChoice
				```

	annotation PBI_ResultType = Table

