table Date
	lineageTag: cccbccf8-a061-46a2-8841-5d0862bad880
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'Parts_Service Sales'[DateInvoice] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence
		lineageTag: f27b276d-bbc0-4f50-810d-2244a9891335

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column Date
		isKey
		formatString: m/d/yyyy
		lineageTag: 24282503-e798-4dcb-be72-16ce3ff3626d
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date

	column Year
		lineageTag: f24f1b5b-b187-453d-9415-f60998b05e7a
		dataCategory: Years
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year]

	column 'Year Quarter Number'
		isHidden
		lineageTag: 76574cf3-a050-4dba-bc3a-f4cb8877c2de
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter Number]

	column 'Year Quarter'
		lineageTag: ace596e9-588b-4a6f-a291-239e3f7171b8
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter]
		sortByColumn: 'Year Quarter Number'

	column Quarter
		lineageTag: e917cca1-f1aa-4472-a2eb-d841cab35037
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Quarter]

	column 'Year Month'
		lineageTag: 402a1a41-a1da-458e-95e5-d20abb7071cf
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		isHidden
		lineageTag: 3d284506-7aed-4fcf-beb3-a6d28c7688d9
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

	column Month
		lineageTag: ce417644-dc45-4924-bd23-161af3316a9c
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Month Number'

	column 'Month Number'
		isHidden
		lineageTag: 5dcf8670-72c9-4b03-8e6d-6b15b3bc4fac
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month Number]

	column 'Day of Week Number'
		isHidden
		lineageTag: 9f4de62b-2614-4db1-8327-0d5ea2f0a6a2
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = DayOfWeek

		annotation SQLBI_FilterSafe = True

	column 'Day of Week'
		lineageTag: a2970a6e-176d-4edb-9288-909fb99d8848
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_FilterSafe = True

	column DateWithTransactions
		isHidden
		lineageTag: dccea9eb-af82-4f60-9f92-6f84dbc81d31
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	hierarchy Calendar
		lineageTag: 5e0c175a-8c17-41d5-8522-2100788bcd93

		level Year
			lineageTag: 0472ab81-ac1c-4ff5-8a87-8983940cdc5b
			column: Year

		level Month
			lineageTag: afa505c1-0700-461f-a8b4-ea2bfa3d8b4d
			column: 'Year Month'

		level Date
			lineageTag: dd4caf9a-6466-4a1d-be79-349296664ed6
			column: Date

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Calendar

