table Date
	lineageTag: 2ae1d4ad-af1a-4ea4-a947-c5b7dbd97037
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'Parts_Service Sales'[DateInvoice] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence
		lineageTag: c25fe09f-c48b-431d-92fc-5577f73c719a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column Date
		isKey
		formatString: m/d/yyyy
		lineageTag: 6496da36-2477-4388-bd1e-37a60b18a8e1
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date

	column Year
		lineageTag: 5ae1b2f8-8d65-42b5-8569-e0ad9d33519f
		dataCategory: Years
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Year]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter Number'
		isHidden
		lineageTag: 89c22eef-03a9-4bcc-8311-e1ef2d445e97
		dataCategory: Quarters
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter Number]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		lineageTag: 11f10da0-fb7e-4bd9-99ba-951104ed463f
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter]
		sortByColumn: 'Year Quarter Number'

	column Quarter
		lineageTag: 805b004d-da9c-45ab-9cdc-765c720cf70a
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Quarter]

	column 'Year Month'
		lineageTag: fa8bcb01-8508-4c9e-83b0-b9c4aa491c04
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		isHidden
		lineageTag: 7009dfcb-40aa-46ca-b5e5-dd30dee039a3
		dataCategory: Months
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

		annotation SummarizationSetBy = Automatic

	column Month
		lineageTag: 459a65db-ad9e-48d8-bc2d-178cee4ff3ea
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Month Number'

	column 'Month Number'
		isHidden
		lineageTag: 84de1d07-8d5c-40e1-840a-e89661bc0848
		dataCategory: MonthOfYear
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Month Number]

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		isHidden
		lineageTag: 8d6bf85c-6c3d-44b2-b250-277a823b464a
		dataCategory: DayOfWeek
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = DayOfWeek

		annotation SQLBI_FilterSafe = True

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		lineageTag: d996cdb6-1db1-412c-9aef-c4a2e3784c2f
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_FilterSafe = True

	column DateWithTransactions
		isHidden
		lineageTag: ccf315b7-7fe2-4913-ad3d-a8d60a194a14
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	hierarchy Calendar
		lineageTag: ed7262af-c79e-47bf-a79e-a0c57dd40775

		level Year
			lineageTag: 429818ae-673b-4c43-9c0d-ebb2ee3475d1
			column: Year

		level Month
			lineageTag: 41a81dd9-dbb2-4e99-95e6-822fd4b2bfb9
			column: 'Year Month'

		level Date
			lineageTag: 57dd74a5-0047-4238-b669-99183a1cce9c
			column: Date

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Calendar

