table PTCLA
	lineageTag: 477467d9-922d-40e9-827f-6b0393514bf4

	column ClaId
		dataType: string
		lineageTag: c5a22e08-969e-4371-955a-0b42448bdb5b
		summarizeBy: none
		sourceColumn: ClaId

		annotation SummarizationSetBy = Automatic

	column Des
		dataType: string
		lineageTag: b1a3d5f0-b8c4-4a75-8096-1a91032f91e6
		summarizeBy: none
		sourceColumn: Des

		annotation SummarizationSetBy = Automatic

	partition PTCLA = m
		mode: import
		source =
				let
				    Source = Sql.Databases("10.250.50.4"),
				    EXCEDE = Source{[Name="EXCEDE"]}[Data],
				    dbo_PTCLA = EXCEDE{[Schema="dbo",Item="PTCLA"]}[Data],
				    #"Capitalized Each Word" = Table.TransformColumns(dbo_PTCLA,{{"Des", Text.Proper, type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Capitalized Each Word",{"ClaId", "Des"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

